In [2]:
import numpy as np

In [4]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a.shape

(2, 3)

In [5]:
import numpy as np

A = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10],
              [11, 12, 13, 14, 15]])
print(A[1, 2: 4])

[8 9]


In [8]:
import numpy as np

A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])

B = A[:, 2]
print(B)

[ 3  7 11 15]


In [10]:
import numpy as np

A = np.array([[1, 1, 2, 3], 
              [4, 5, 1, 4], 
              [1, 9, 10, 11]])

print(A.sum(axis = 0))

[ 6 15 13 18]


In [12]:
import numpy as np

A = np.array([[1, 1, 2, 3], 
              [4, 5, 1, 4], 
              [1, 9, 10, 11]])

print(A.sum(axis = 1))

[ 7 14 31]


In [14]:
A = np.array(([1, 2, 3]))
B = np.array([[4, 5, 6]])
print(A + B)

[[5 7 9]]


In [16]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
z = x @ y
print(z)

32


In [18]:
z = np.dot(x, y)
print(z)

32


In [19]:
w = np.zeros(5)
w += 2
print(w)

[2. 2. 2. 2. 2.]


In [21]:
x = np.linspace(-1, 1, 5)
y = 2 * x + 4
print(y)

[2. 3. 4. 5. 6.]


In [23]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7,8],[9,10],[11,12]])
print(a@b)

[[ 58  64]
 [139 154]]


In [26]:
a = np.array([[1,2],[1,3],[1,5]])
x = np.array([1,2])
b = np.array([3,4,5])
print("shape of a: ", a.shape, "\nshape of x: ", x.shape, "\nshape of b: ", b.shape)
print(a@x-b)

shape of a:  (3, 2) 
shape of x:  (2,) 
shape of b:  (3,)
[2 3 6]


In [40]:
M = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b = np.array([1,2,3,4])
print(b.shape)
b = np.expand_dims(b, axis=0)
print(b.shape)
print(M+b)



(4,)
(1, 4)
[[ 2  4  6  8]
 [ 6  8 10 12]
 [10 12 14 16]]


In [41]:
M = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b = np.array([1,2,3])
print(b.shape)
b = np.expand_dims(b, axis=1)
print(b.shape)
print(M+b)

(3,)
(3, 1)
[[ 2  3  4  5]
 [ 7  8  9 10]
 [12 13 14 15]]
